"""create users and documents tables

Revision ID: 2e47be4a226a
Revises: 68f8abc9308d
Create Date: 2026-03-28 18:24:18.582405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '2e47be4a226a'
down_revision: Union[str, Sequence[str], None] = '68f8abc9308d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('filename', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('status', sa.String(), nullable=True))
    op.alter_column('documents', 'embedding',
           existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
           type_=Vector(1536),
           existing_nullable=True)

    op.add_column('users', sa.Column('password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('role', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'password')
    op.alter_column('documents', 'embedding',
           existing_type=Vector(1536),
           type_=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
           existing_nullable=True)
    op.drop_column('documents', 'status')
    op.drop_column('documents', 'filename')
    # ### end Alembic commands ###
